description = "Base builder for 20 stack, based on ubuntu:20.04 base image"

[lifecycle]
version = "0.11.3"

[[buildpacks]]
  id = "drycc/ruby"
  version = "0.0.1"
  uri = "./buildpacks/ruby"

[[order]]
[[order.group]]
id = "drycc/ruby"
version = "0.0.1"

[[buildpacks]]
  id = "drycc/python"
  version = "0.0.1"
  uri = "./buildpacks/python"

[[order]]
[[order.group]]
id = "drycc/python"
version = "0.0.1"

[stack]
id = "drycc-20"
build-image = "registry.uucin.com/lijianguo/pack:20-build"
run-image = "registry.uucin.com/lijianguo/pack:20"
