ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG pack_uid=1000
ARG pack_gid=1000

ADD rootfs /

RUN groupadd drycc --gid ${pack_gid} && \
  useradd drycc -u ${pack_uid} -g ${pack_gid} -s /bin/bash -m
RUN mkdir /app && \
  chown drycc:drycc /app /usr/src /var/lib
RUN chmod +x /usr/local/bin/* && \
  install-tools.sh

ENV CNB_USER_ID=${pack_uid}
ENV CNB_GROUP_ID=${pack_gid}

ARG STACK
ENV STACK "${STACK}"
ENV CNB_STACK_ID "${STACK}"
LABEL io.buildpacks.stack.id="${STACK}"

USER drycc
