ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN ln -s /workspace /app

ARG pack_uid=1000
ARG pack_gid=1000

RUN groupadd drycc --gid ${pack_gid} && \
  useradd drycc -u ${pack_uid} -g ${pack_gid} -s /bin/bash -m

RUN apt-get update && apt-get install -y --no-install-recommends \
            binutils \
            gdal-bin \
            libproj-dev \
            libsqlite3-dev \
            sqlite3

ARG STACK
LABEL io.buildpacks.stack.id="${STACK}"
USER drycc
ENV HOME /app
