# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "drycc/java-gradle"
version = "0.0.1"
name = "Java Gradle Buildpack"
homepage = "https://github.com/drycc/pack-images/tree/main/buildpacks/java-gradle"

# Stacks that the buildpack will work with
[[stacks]]
id = "drycc-20"
