#!/bin/sh
set -e

dir="${php_layer_dir}"/src/php

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Manage php source tarball lifecycle."
	echo
	echo "Commands:"
	echo "   extract  extract php source tarball into directory $dir if not already done."
	echo "   delete   delete extracted php source located into $dir if not already done."
	echo
}

case "$1" in
	extract)
	  echo "source php_layer_dir ${php_layer_dir}"
		mkdir -p "$dir"
		if [ ! -f "$dir/.extracted" ]; then
		  php_url=https://www.php.net/distributions/php-"${php_version}".tar.xz
      wget -q -O - "${php_url}" | tar -xJf - --strip-components=1 -C "${dir}"
			touch "$dir/.extracted"
		fi
		;;

	delete)
		rm -rf "$dir"
		;;

	*)
		usage
		exit 1
		;;
esac