#!/usr/bin/env bash

# 4. MAKE MAVEN M2 CACHE LAYER
maven_build() {
  m2_layer_dir="${layers_dir}/maven_m2"
  if [[ ! -d "${m2_layer_dir}" ]]; then
    mkdir -p "${m2_layer_dir}"
    echo "cache = true" > "${m2_layer_dir}.toml"
  fi
  ln -s "${m2_layer_dir}" "$HOME/.m2"
  # 5. RUN BUILD
  MAVEN_OPTS="${MAVEN_OPTS:-"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"}"

  if [[ -x mvnw ]]; then
    echo "---> Running Maven Wrapper"
    ./mvnw clean install -B -DskipTests
  else
    maven_url="https://apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz"
    maven_version="3.5.4"
    maven_layer_dir="${layers_dir}/maven"
    if [[ -f "${layers_dir}/maven.toml" ]]; then
      cached_maven_url=$(cat "${maven_layer_dir}.toml" | yj -t | jq -r .metadata.url 2>/dev/null || echo 'Maven TOML parsing failed')
    fi
    if [[ "${maven_url}" != "${cached_maven_url}" ]] ; then
      echo "---> Installing Maven"
      rm -rf "${maven_layer_dir}"
      mkdir -p "${maven_layer_dir}"
      wget -q -O - "${maven_url}" | tar pxz -C "${maven_layer_dir}" --strip-components=1
      cat > "${maven_layer_dir}.toml" << EOF
launch = true
build = true
cache = true
[metadata]
version = "${maven_version}"
url = "${maven_url}"
EOF
    fi
    export PATH="${PATH}:${layers_dir}/maven/bin"
    echo "---> Running Maven Wrapper"
    mvn clean install -B -DskipTests
  fi
}

